### ISSUE TITLE
Some bug when push github page

### ISSUE THREAD

**Issue by zytx121** [MoeFE/vue-aplayer#2]
![image](https://user-images.githubusercontent.com/10410257/28606600-6005fcec-720a-11e7-925f-504a9ba0c3f8.png)

我把vue-aplayer加到我的项目里面，本地测试是好的，但是 npm run build 后push到github上报错，页面无法显示。。

**Comment by zytx121** [comment]
是按照doc里面的方法引入的
![image](https://user-images.githubusercontent.com/10410257/28606739-1108a2c4-720b-11e7-81ca-2cedab93bac6.png)

**Comment by u3u** [comment]
https://github.com/MoeFE/Lyric
我这个是正常的 方便发一个测试仓库出来吗

**Comment by zytx121** [comment]
测试仓库：https://github.com/zytx121/vue-justice_eternal

clone 
npm install

阿里嘎多！

**Comment by u3u** [comment]
> 我有一句妈卖批我一定要讲！

看编译后的代码看得快吐血了 最后怀疑是 [vuejs/vue-touch](https://github.com/vuejs/vue-touch) 的问题
然后搜了一下 issues 果然发现了同样的问题 https://github.com/vuejs/vue-touch/issues/75

其实之前早就有怀疑是它的问题 但因为它是官方写的库 出于信任并没有第一时间去掉它测试
然后刚才去掉后测试没问题了 定位到问题了就好说 接下来我自己撸一个 vue-touch 就好了

**Comment by zytx121** [comment]
抱紧大佬大腿(◦˙▽˙◦)

**Comment by u3u** [comment]
[vue-aplayer-plugin@1.1.0](http://npm.elemecdn.com/vue-aplayer-plugin@1.1.0/dist/APlayer.min.js)
 已发布 请更新依赖后再试试
